import React from 'react';
import { 
  ShieldCheck, 
  PhoneCall, 
  MapPin, 
  Sparkles, 
  ArrowRight
} from 'lucide-react';

interface FooterProps {
  onNavigate?: (view: string) => void;
}

export const Footer: React.FC<FooterProps> = ({ onNavigate }) => {
  const handleNav = (view: string, e: React.MouseEvent) => {
    e.preventDefault();
    if (onNavigate) {
      onNavigate(view);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  return (
    <footer className="hidden sm:block bg-[#1C1917] text-stone-300 pt-12 pb-8 border-t border-stone-800">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
        
        {/* 3 Pillars Summary */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 pb-10 border-b border-stone-800">
          <div className="flex items-start space-x-3">
            <div className="w-10 h-10 rounded-xl bg-[#1B4332] text-white flex items-center justify-center shrink-0">
              <MapPin className="w-5 h-5 text-emerald-300" />
            </div>
            <div>
              <h4 className="font-bold text-white text-sm">Travel Locally & Affordably</h4>
              <p className="text-xs text-stone-400 mt-1 leading-relaxed">
                Step-by-step local bus numbers, boarding stands, and community-reported fares. Save on local transit.
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3">
            <div className="w-10 h-10 rounded-xl bg-[#1B4332] text-white flex items-center justify-center shrink-0">
              <Sparkles className="w-5 h-5 text-amber-300" />
            </div>
            <div>
              <h4 className="font-bold text-white text-sm">Platform Verification</h4>
              <p className="text-xs text-stone-400 mt-1 leading-relaxed">
                Community reports start as PENDING. Only audited entries carry official verification stamps with dates.
              </p>
            </div>
          </div>

          <div className="flex items-start space-x-3">
            <div className="w-10 h-10 rounded-xl bg-[#1B4332] text-white flex items-center justify-center shrink-0">
              <ShieldCheck className="w-5 h-5 text-emerald-300" />
            </div>
            <div>
              <h4 className="font-bold text-white text-sm">Traveler Feedback & Re-Check</h4>
              <p className="text-xs text-stone-400 mt-1 leading-relaxed">
                Rate accuracy with 1–5 stars and report outdated info to trigger re-verification.
              </p>
            </div>
          </div>
        </div>

        {/* Main Footer Links & Brand Section */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 py-4 border-b border-stone-800 text-xs">
          
          {/* Brand Col */}
          <div className="space-y-3">
            <div 
              className="flex items-center space-x-2 cursor-pointer"
              onClick={(e) => handleNav('home', e)}
            >
              <div className="w-8 h-8 rounded-xl bg-[#1B4332] text-white flex items-center justify-center font-black text-base shadow-xs">
                L
              </div>
              <span className="font-black text-xl text-white tracking-tight">LocalLens</span>
            </div>
            <p className="font-extrabold text-emerald-400 text-xs uppercase tracking-wide">
              TRAVEL LIKE A LOCAL.
            </p>
            <p className="text-stone-400 text-xs italic">
              Go like someone who knows the place.
            </p>
            <p className="text-stone-400 leading-relaxed text-[11px]">
              Practical local travel intelligence generated by verified citizens and audited by platform desks.
            </p>
          </div>

          {/* Navigation Links */}
          <div>
            <h5 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Navigation</h5>
            <ul className="space-y-2 text-stone-400">
              <li>
                <a href="#home" onClick={(e) => handleNav('home', e)} className="hover:text-white transition-colors">
                  Home
                </a>
              </li>
              <li>
                <a href="#destinations" onClick={(e) => handleNav('destination', e)} className="hover:text-white transition-colors">
                  Destinations
                </a>
              </li>
              <li>
                <a href="#transport" onClick={(e) => handleNav('transport', e)} className="hover:text-white transition-colors">
                  Transport
                </a>
              </li>
              <li>
                <a href="#stays" onClick={(e) => handleNav('stays', e)} className="hover:text-white transition-colors">
                  Stays & Food
                </a>
              </li>
              <li>
                <a href="#planner" onClick={(e) => handleNav('planner', e)} className="hover:text-white transition-colors flex items-center space-x-1">
                  <Sparkles className="w-3 h-3 text-emerald-400" />
                  <span>AI Planner</span>
                </a>
              </li>
              <li>
                <a href="#community" onClick={(e) => handleNav('missions', e)} className="hover:text-white transition-colors">
                  Community Missions
                </a>
              </li>
              <li>
                <a href="#verification" onClick={(e) => handleNav('verification', e)} className="hover:text-white transition-colors">
                  Verification Desk
                </a>
              </li>
            </ul>
          </div>

          {/* Community Col */}
          <div>
            <h5 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Community & Scouts</h5>
            <ul className="space-y-2 text-stone-400">
              <li>
                <a href="#contributor" onClick={(e) => handleNav('contributor', e)} className="hover:text-white transition-colors flex items-center space-x-1">
                  <span>Become a Local Scout</span>
                  <ArrowRight className="w-3 h-3 text-emerald-400 ml-1" />
                </a>
              </li>
              <li>
                <a href="#share" onClick={(e) => handleNav('share-knowledge', e)} className="hover:text-white transition-colors">
                  Share Local Knowledge
                </a>
              </li>
              <li>
                <a href="#explore" onClick={(e) => handleNav('explore-knowledge', e)} className="hover:text-white transition-colors">
                  Explore Ground Tips
                </a>
              </li>
              <li>
                <a href="#profile" onClick={(e) => handleNav('profile', e)} className="hover:text-white transition-colors">
                  Traveler Profile & Saved
                </a>
              </li>
            </ul>
          </div>

          {/* Emergency & Support */}
          <div>
            <h5 className="font-bold text-white uppercase text-[11px] tracking-wider mb-3">Support & Safety</h5>
            <div className="bg-stone-900 p-3.5 rounded-2xl border border-stone-800 space-y-2.5">
              <div className="flex items-center text-amber-400 font-bold">
                <PhoneCall className="w-3.5 h-3.5 mr-1.5" />
                <span>Tourist Helpline: 1363</span>
              </div>
              <p className="text-[11px] text-stone-400">
                National Emergency: 112 (Police & Ambulance)
              </p>
              <div className="pt-2 border-t border-stone-800 text-[10px] text-stone-500 space-y-1">
                <div>Data Integrity Rules</div>
                <div>Terms & Privacy Policy</div>
              </div>
            </div>
          </div>

        </div>

        {/* Bottom copyright */}
        <div className="pt-2 flex flex-wrap items-center justify-between gap-4 text-[11px] text-stone-500">
          <p>© 2026 LocalLens Travel Intelligence. Travel like someone who knows the place.</p>
          <div className="flex items-center space-x-4">
            <span>Built with Ground Truth</span>
            <span>•</span>
            <span>Supabase PostgreSQL Protected</span>
          </div>
        </div>

      </div>
    </footer>
  );
};
